# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [6]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

In [2]:
x = np.array(range(20)) 
y = x * 2 - 1

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [3]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1)(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)

# 컴파일 해주렴
model.compile(loss='mse', optimizer='adam')

In [4]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

Epoch 1/10
1/1 [==============================] - 1s 751ms/step - loss: 9.2884
Epoch 2/10
1/1 [==============================] - 0s 14ms/step - loss: 9.2172
Epoch 3/10
1/1 [==============================] - 0s 11ms/step - loss: 9.1463
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 9.0757
Epoch 5/10
1/1 [==============================] - 0s 13ms/step - loss: 9.0054
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 8.9354
Epoch 7/10
1/1 [==============================] - 0s 10ms/step - loss: 8.8657
Epoch 8/10
1/1 [==============================] - 0s 13ms/step - loss: 8.7964
Epoch 9/10
1/1 [==============================] - 0s 9ms/step - loss: 8.7273
Epoch 10/10
1/1 [==============================] - 0s 11ms/step - loss: 8.6586


In [8]:
# 결과 출력해줘!
print(y)
print(np.around(model.predict(x).reshape(-1,)) )

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]
1/1 [==============================] - 0s 23ms/step
[ 0.  2.  3.  5.  7.  8. 10. 12. 13. 15. 17. 18. 20. 22. 23. 25. 27. 28.
 30. 32.]


## Now, Your turn!

In [9]:
import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow import keras

In [10]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [17]:
## functional API
# clear session
keras.backend.clear_session()
# layer set
il = keras.layers.Input(shape=1)
ol = keras.layers.Dense(1)(il)
# model set
keras.models.Model(inputs=il, outputs=ol)
# model compile
model.compile(loss='mse',optimizer='Adam')
# summary
model.summary()

Model: "model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 input_1 (InputLayer)        [(None, 1)]               0         
                                                                 
 dense (Dense)               (None, 1)                 2         
                                                                 
Total params: 2
Trainable params: 2
Non-trainable params: 0
_________________________________________________________________


In [18]:
model.fit(x,y,epochs=10)

Epoch 1/10
1/1 [==============================] - 0s 470ms/step - loss: 61.0922
Epoch 2/10
1/1 [==============================] - 0s 9ms/step - loss: 60.9578
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 60.8237
Epoch 4/10
1/1 [==============================] - 0s 9ms/step - loss: 60.6899
Epoch 5/10
1/1 [==============================] - 0s 9ms/step - loss: 60.5565
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 60.4233
Epoch 7/10
1/1 [==============================] - 0s 9ms/step - loss: 60.2904
Epoch 8/10
1/1 [==============================] - 0s 9ms/step - loss: 60.1579
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 60.0257
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 59.8938


## Quick Logistic Regression!

In [ ]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [ ]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)

print(x)
print(y)

In [ ]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# 레이어들을 사슬로 연결하 듯이 연결!
input_layer = keras.layers.Input(shape=(1,))
output_layer = keras.layers.Dense(1, activation='sigmoid')(input_layer)

# 모델의 시작과 끝을 지정
model = keras.models.Model(inputs=input_layer, outputs=output_layer)


# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [ ]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!
print(y)
print(model.predict(x).reshape(-1,) )

## Now, Your turn!

In [ ]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)