# Keras로 Linear&Logistic Regression 맛보기!
---
#### 실습목표
1. keras의 모델링 아이디어를 이해한다.
2. 모든 코드를 이해한다.

## Quick Linear Regression!

In [1]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [3]:
x = np.array(range(20))
y = x * 2 - 1 

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [4]:
x.shape, y.shape

((20,), (20,))

In [5]:
## sequential API
# 1번 청소 : 이미 만들어진 모델이 있다면 그 모델을 없애줘 (세션 클리어)
keras.backend.clear_session()

# 2번 모델 선언 (모델 발판 생성)
model = keras.models.Sequential()

# 3번 모델 블록 조립 (모델 레이어 쌓기)
model.add( keras.layers.Input(shape=(1,)) )
model.add( keras.layers.Dense(1) )

## 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,)) )

### 컴파일 전에 실행시켜야 자동완성을 쓸 수 있음

# 4번 컴파일 
model.compile(loss='mse',
              optimizer='adam')

In [6]:
model.fit(x, y, epochs=10, verbose=1) # verbose = 학습과정을 보여줌, default = 1, 1 일 경우 학습과정을 상세히 보여줌

Epoch 1/10
1/1 [==============================] - 1s 550ms/step - loss: 104.8407
Epoch 2/10
1/1 [==============================] - 0s 20ms/step - loss: 104.5966
Epoch 3/10
1/1 [==============================] - 0s 9ms/step - loss: 104.3528
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 104.1093
Epoch 5/10
1/1 [==============================] - 0s 12ms/step - loss: 103.8661
Epoch 6/10
1/1 [==============================] - 0s 9ms/step - loss: 103.6233
Epoch 7/10
1/1 [==============================] - 0s 7ms/step - loss: 103.3807
Epoch 8/10
1/1 [==============================] - 0s 7ms/step - loss: 103.1385
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 102.8966
Epoch 10/10
1/1 [==============================] - 0s 8ms/step - loss: 102.6550


In [7]:
print(y)

[-1  1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37]


In [8]:
model.predict(x).reshape(-1)

1/1 [==============================] - 0s 65ms/step


array([9.9958936e-03, 1.0228882e+00, 2.0357804e+00, 3.0486727e+00,
       4.0615649e+00, 5.0744572e+00, 6.0873494e+00, 7.1002417e+00,
       8.1131334e+00, 9.1260252e+00, 1.0138918e+01, 1.1151811e+01,
       1.2164702e+01, 1.3177594e+01, 1.4190487e+01, 1.5203380e+01,
       1.6216272e+01, 1.7229164e+01, 1.8242056e+01, 1.9254950e+01],
      dtype=float32)

## Now, Your turn!

In [9]:
import numpy as np
import tensorflow as tf
from tensorflow import keras

In [10]:
x = np.array(range(20)) 
y = x * (-3) + 10

print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 10   7   4   1  -2  -5  -8 -11 -14 -17 -20 -23 -26 -29 -32 -35 -38 -41
 -44 -47]


In [12]:
x.shape, y.shape

((20,), (20,))

In [15]:
# 1. 청소
keras.backend.clear_session()
# 2. 모델 선언
model = keras.models.Sequential()
#3 모델 쌓기
model.add(keras.layers.Input(shape=1))
model.add(keras.layers.Dense(1))
#4 컴파일
model.compile(loss='mse',optimizer='Adam')

In [27]:
model.fit(x,y,epochs=5000,verbose=0)

In [28]:
y_pred = model.predict(x)

1/1 [==============================] - 0s 35ms/step


In [29]:
y_pred.reshape(-1)

array([  3.0184002,   0.5599587,  -1.8984828,  -4.356924 ,  -6.815366 ,
        -9.273808 , -11.732248 , -14.190691 , -16.649132 , -19.107573 ,
       -21.566015 , -24.024456 , -26.482897 , -28.94134  , -31.399782 ,
       -33.858223 , -36.316666 , -38.77511  , -41.233543 , -43.691986 ],
      dtype=float32)

## Quick Logistic Regression!

In [30]:
import tensorflow as tf
from tensorflow import keras

import numpy as np

In [31]:
x = np.array(range(20)) 
y = np.array([0]*10 + [1]*10)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]


In [32]:
# 혹시 이미 그려둔 그래프가 있다면 날려줘!
keras.backend.clear_session()

# model에 순차적으로 레이어를 쌓아가겠다는 의도!
model = keras.models.Sequential()

# model에 인풋 값을 받는 레이어를 넣음
model.add( keras.layers.Input(shape=(1,)) )
# model에 Dense 레이어를 넣을거야 (최초의 레이어) : weight를 곱하고, bias를 더해주는 과정
model.add( keras.layers.Dense(1, activation='sigmoid') )


# 오리지널 Sequential API
# model.add( keras.layers.Dense(1, input_shape=(1,), activation='sigmoid') )

# 컴파일 해주렴
model.compile(loss='binary_crossentropy', metrics=['accuracy'],
              optimizer='adam')

In [34]:
# 데이터를 넣어서 학습시키자!
model.fit(x, y, epochs=10, verbose=1)

# 결과 출력해줘!


Epoch 1/10
1/1 [==============================] - 0s 14ms/step - loss: 0.8820 - accuracy: 0.5500
Epoch 2/10
1/1 [==============================] - 0s 8ms/step - loss: 0.8798 - accuracy: 0.5500
Epoch 3/10
1/1 [==============================] - 0s 10ms/step - loss: 0.8775 - accuracy: 0.5500
Epoch 4/10
1/1 [==============================] - 0s 10ms/step - loss: 0.8753 - accuracy: 0.5500
Epoch 5/10
1/1 [==============================] - 0s 10ms/step - loss: 0.8730 - accuracy: 0.5500
Epoch 6/10
1/1 [==============================] - 0s 10ms/step - loss: 0.8708 - accuracy: 0.5500
Epoch 7/10
1/1 [==============================] - 0s 12ms/step - loss: 0.8686 - accuracy: 0.5500
Epoch 8/10
1/1 [==============================] - 0s 8ms/step - loss: 0.8663 - accuracy: 0.5500
Epoch 9/10
1/1 [==============================] - 0s 8ms/step - loss: 0.8641 - accuracy: 0.5500
Epoch 10/10
1/1 [==============================] - 0s 10ms/step - loss: 0.8619 - accuracy: 0.5500
[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1

In [35]:
print(y)
print(model.predict(x).reshape(-1))

[0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1]
1/1 [==============================] - 0s 18ms/step
[0.49500626 0.57458186 0.65047216 0.71943504 0.77940565 0.8295939
 0.8702643  0.9023703  0.9271956  0.9460855  0.9602842  0.9708587
 0.97868025 0.98443615 0.98865604 0.9917414  0.9939927  0.995633
 0.9968268  0.997695  ]


## Now, Your turn!

In [38]:
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np

In [43]:
x = np.array(range(40)) 
y = np.array([0]*20 + [1]*20)
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1]


In [44]:
# 버퍼 초기화
keras.backend.clear_session()
# 2. 모델 선언
model = keras.models.Sequential()
# 3. 모델 레이어 쌓기
model.add(keras.layers.Input(shape=(1,)))
model.add(keras.layers.Dense(1,activation='sigmoid'))
# 4. 컴파일
model.compile(loss='binary_crossentropy',metrics=['accuracy'],optimizer='Adam')

In [46]:
model.fit(x,y,epochs=10,verbose=0)
# verbose=0을 하면 keras.callbacks.History에 정보가 저장된다