# Keras로 Linear&Logistic Regression 조금 더 맛보기
---

In [31]:
import tensorflow as tf
from tensorflow import keras

import numpy as np
import pandas as pd

##Linear Regression on 쬐금 더 어려운 데이터

In [32]:
from sklearn.datasets import load_boston

In [33]:
boston = load_boston()

/usr/local/lib/python3.8/dist-packages/sklearn/utils/deprecation.py:87: FutureWarning: Function load_boston is deprecated; `load_boston` is deprecated in 1.0 and will be removed in 1.2.

    The Boston housing prices dataset has an ethical problem. You can refer to
    the documentation of this function for further details.

    The scikit-learn maintainers therefore strongly discourage the use of this
    dataset unless the purpose of the code is to study and educate about
    ethical issues in data science and machine learning.

    In this special case, you can fetch the dataset from the original
    source::

        import pandas as pd
        import numpy as np


        data_url = "http://lib.stat.cmu.edu/datasets/boston"
        raw_df = pd.read_csv(data_url, sep="\s+", skiprows=22, header=None)
        data = np.hstack([raw_df.values[::2, :], raw_df.values[1::2, :2]])
        target = raw_df.values[1::2, 2]

    Alternative datasets include the California housing dataset (i.e.

In [34]:
x = boston.data
y = boston.target

x.shape, y.shape

((506, 13), (506,))

In [35]:
x.shape[1]

13

In [36]:
#1. 버퍼 초기화
keras.backend.clear_session()
#2. 모델 선언
model = keras.models.Sequential()
#3 레이어 선언
model.add(keras.layers.Input(shape=x.shape[1]))
model.add(keras.layers.Dense(1))
#4 . 컴파일
model.compile(loss='mse',optimizer='Adam')

In [37]:
model.fit(x,y,epochs=5000)

스트리밍 출력 내용이 길어서 마지막 5000줄이 삭제되었습니다.
16/16 [==============================] - 0s 3ms/step - loss: 24.1391
Epoch 2502/5000
16/16 [==============================] - 0s 3ms/step - loss: 23.9988
Epoch 2503/5000
16/16 [==============================] - 0s 3ms/step - loss: 24.4164
Epoch 2504/5000
16/16 [==============================] - 0s 3ms/step - loss: 24.0006
Epoch 2505/5000
16/16 [==============================] - 0s 2ms/step - loss: 24.0269
Epoch 2506/5000
16/16 [==============================] - 0s 3ms/step - loss: 24.1207
Epoch 2507/5000
16/16 [==============================] - 0s 4ms/step - loss: 24.4234
Epoch 2508/5000
16/16 [==============================] - 0s 3ms/step - loss: 23.9375
Epoch 2509/5000
16/16 [==============================] - 0s 3ms/step - loss: 24.1372
Epoch 2510/5000
16/16 [==============================] - 0s 3ms/step - loss: 23.9415
Epoch 2511/5000
16/16 [==============================] - 0s 3ms/step - loss: 24.1158
Epoch 2512/5000
16/16 [======================

In [38]:
y_pred = model.predict(x).reshape(-1)

16/16 [==============================] - 0s 3ms/step


In [47]:
y_pred[30:50],y[30:50]

(array([2.6387395e-10, 6.1496056e-04, 2.9272110e-07, 4.4491776e-12,
        1.2798712e-05, 1.3132011e-04, 8.2484734e-01, 9.9979895e-01,
        9.6230263e-01, 7.4436599e-01, 4.9033144e-01, 9.1278028e-01,
        1.0450845e-08, 5.8104023e-03, 6.9989789e-01, 4.8633048e-08,
        9.9904680e-01, 2.3436323e-01, 9.9395651e-01, 9.4634646e-01],
       dtype=float32),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1]))

## Logistic Regression 쬐금 더 어려운 데이터

In [40]:
from sklearn.datasets import load_breast_cancer

In [41]:
cancer = load_breast_cancer()

In [42]:
x = cancer.data
y = cancer.target

# 모양 확인해볼 것
x.shape,y.shape

((569, 30), (569,))

In [43]:
# 1 버퍼 초기화
keras.backend.clear_session()
# 2 모델 선언
model = keras.models.Sequential()
#3 레이어 선언
model.add( keras.layers.Input(shape=(30,)) )
model.add( keras.layers.Dense(1,activation='sigmoid'))
#4 컴파일
model.compile(loss='binary_crossentropy',metrics=['accuracy'],optimizer='adam')

In [44]:
model.fit(x,y,epochs=500)

Epoch 1/500
18/18 [==============================] - 1s 4ms/step - loss: 2.2458 - accuracy: 0.8102
Epoch 2/500
18/18 [==============================] - 0s 3ms/step - loss: 2.0591 - accuracy: 0.7944
Epoch 3/500
18/18 [==============================] - 0s 3ms/step - loss: 1.9785 - accuracy: 0.8084
Epoch 4/500
18/18 [==============================] - 0s 3ms/step - loss: 1.9681 - accuracy: 0.8032
Epoch 5/500
18/18 [==============================] - 0s 3ms/step - loss: 1.8734 - accuracy: 0.8418
Epoch 6/500
18/18 [==============================] - 0s 3ms/step - loss: 1.8157 - accuracy: 0.8102
Epoch 7/500
18/18 [==============================] - 0s 3ms/step - loss: 1.7356 - accuracy: 0.8401
Epoch 8/500
18/18 [==============================] - 0s 3ms/step - loss: 1.7006 - accuracy: 0.8260
Epoch 9/500
18/18 [==============================] - 0s 4ms/step - loss: 1.6472 - accuracy: 0.8313
Epoch 10/500
18/18 [==============================] - 0s 4ms/step - loss: 1.5903 - accuracy: 0.8295
Epoch 11/

In [45]:
y_pred = model.predict(x).reshape(-1)

18/18 [==============================] - 0s 2ms/step


In [48]:
y_pred[30:50],y[30:50]

(array([2.6387395e-10, 6.1496056e-04, 2.9272110e-07, 4.4491776e-12,
        1.2798712e-05, 1.3132011e-04, 8.2484734e-01, 9.9979895e-01,
        9.6230263e-01, 7.4436599e-01, 4.9033144e-01, 9.1278028e-01,
        1.0450845e-08, 5.8104023e-03, 6.9989789e-01, 4.8633048e-08,
        9.9904680e-01, 2.3436323e-01, 9.9395651e-01, 9.4634646e-01],
       dtype=float32),
 array([0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1]))