# 멀티클래스 분류 연습 (over 2진분류)
---
![iris_flower](https://www.embedded-robotics.com/wp-content/uploads/2022/01/Iris-Dataset-Classification-1024x367.png)

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape, y.shape

((150, 4), (150,))

In [5]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [6]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [8]:
# One-Hot Encoding
import tensorflow as tf
from tensorflow.keras.utils import to_categorical

In [9]:
y = to_categorical(y, 3)

In [10]:
x.shape, y.shape

((150, 4), (150, 3))

In [11]:
y[:5]

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]], dtype=float32)

In [12]:
from tensorflow import keras
import tensorflow as tf
import numpy as np
import pandas as pd

## 1번. Sequential API style로 모델링 하세요

- loss = 'categorical_crossentropy' 사용!

In [20]:
keras.backend.clear_session()
model = keras.models.Sequential()
model.add(keras.Input(shape=4))
model.add(keras.layers.Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',metrics=['acc'],optimizer='adam')
#양념
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [26]:
keras.backend.clear_session()
model = keras.models.Sequential()
model.add(keras.Input(shape=4))
model.add(keras.layers.Dense(3,activation='softmax'))
model.compile(loss='categorical_crossentropy',metrics=['acc'],optimizer=keras.optimizers.Adam()) #adam에서 탭을 누르면 정보를 볼 수 있다 파이토치에서 보던 그거 나오네
#양념
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 3)                 15        
                                                                 
Total params: 15
Trainable params: 15
Non-trainable params: 0
_________________________________________________________________


In [21]:
model.fit(x,y,epochs=30)

Epoch 1/30
5/5 [==============================] - 0s 5ms/step - loss: 2.8598 - acc: 0.3333
Epoch 2/30
5/5 [==============================] - 0s 3ms/step - loss: 2.7552 - acc: 0.3333
Epoch 3/30
5/5 [==============================] - 0s 3ms/step - loss: 2.6503 - acc: 0.3333
Epoch 4/30
5/5 [==============================] - 0s 3ms/step - loss: 2.5479 - acc: 0.3333
Epoch 5/30
5/5 [==============================] - 0s 3ms/step - loss: 2.4504 - acc: 0.3333
Epoch 6/30
5/5 [==============================] - 0s 3ms/step - loss: 2.3454 - acc: 0.3333
Epoch 7/30
5/5 [==============================] - 0s 4ms/step - loss: 2.2513 - acc: 0.3333
Epoch 8/30
5/5 [==============================] - 0s 4ms/step - loss: 2.1518 - acc: 0.3333
Epoch 9/30
5/5 [==============================] - 0s 3ms/step - loss: 2.0573 - acc: 0.3333
Epoch 10/30
5/5 [==============================] - 0s 3ms/step - loss: 1.9691 - acc: 0.3333
Epoch 11/30
5/5 [==============================] - 0s 3ms/step - loss: 1.8759 - acc: 0.33

In [22]:
y_pred = model.predict(x)

5/5 [==============================] - 0s 2ms/step


In [23]:
y_pred[:5],y[:5]

(array([[0.81133527, 0.15443464, 0.03423013],
        [0.7930495 , 0.15290669, 0.05404382],
        [0.7793067 , 0.17609459, 0.04459874],
        [0.77174264, 0.17400734, 0.05424999],
        [0.80397654, 0.164186  , 0.03183741]], dtype=float32),
 array([[1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.],
        [1., 0., 0.]], dtype=float32))

## 2번. Functional API style로 모델링 하세요

In [ ]:
x.shape, y.shape