# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [1]:
from sklearn.datasets import fetch_california_housing

In [2]:
california = fetch_california_housing()

In [3]:
x = california.data
y = california.target

In [4]:
x.shape, y.shape

((20640, 8), (20640,))

In [5]:
#####################
# 라이브러리 불러오기
#####################
from tensorflow import keras
import tensorflow as tf

In [13]:
########
# 모델링
########
# 클리어세션
keras.backend.clear_session()
# 모델선언
model = keras.models.Sequential()
# 레이어선언
model.add( keras.layers.Input(shape=(8,)) )
model.add( keras.layers.Dense(1) )
# 컴파일
model.compile(loss='mse',optimizer='Adam',metrics=['mae'])

In [14]:
###########
# 모델 학습
###########
model.fit(x,y,epochs=50)


Epoch 1/50
645/645 [==============================] - 1s 1ms/step - loss: 169.0010 - mae: 8.9398
Epoch 2/50
645/645 [==============================] - 1s 1ms/step - loss: 19.3004 - mae: 3.4994
Epoch 3/50
645/645 [==============================] - 1s 1ms/step - loss: 7.1033 - mae: 2.0752
Epoch 4/50
645/645 [==============================] - 1s 1ms/step - loss: 2.3518 - mae: 1.1631
Epoch 5/50
645/645 [==============================] - 1s 1ms/step - loss: 1.1407 - mae: 0.8222
Epoch 6/50
645/645 [==============================] - 1s 1ms/step - loss: 0.8843 - mae: 0.7284
Epoch 7/50
645/645 [==============================] - 1s 2ms/step - loss: 0.7483 - mae: 0.6688
Epoch 8/50
645/645 [==============================] - 1s 2ms/step - loss: 0.7193 - mae: 0.6524
Epoch 9/50
645/645 [==============================] - 1s 2ms/step - loss: 0.7280 - mae: 0.6522
Epoch 10/50
645/645 [==============================] - 1s 2ms/step - loss: 0.7587 - mae: 0.6603
Epoch 11/50
645/645 [=========================

In [15]:
###########
# 모델 예측
###########
y_pred = model.predict(x).reshape(-1)

645/645 [==============================] - 1s 1ms/step


In [16]:
y_pred[:10],y[:10]

(array([4.1192513, 3.6682115, 3.6059957, 3.1350956, 2.1963255, 2.5199203,
        2.1523995, 1.9677615, 1.4017751, 2.1422703], dtype=float32),
 array([4.526, 3.585, 3.521, 3.413, 3.422, 2.697, 2.992, 2.414, 2.267,
        2.611]))

# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [28]:
########
# 모델링
########
# session clear
keras.backend.clear_session()
# model
model = keras.models.Sequential()
# layers
model.add( keras.layers.Input(shape=(8,)) )
model.add( keras.layers.Dense(32, activation='relu') )
model.add( keras.layers.Dense(16, activation='relu') )
model.add( keras.layers.Dense(1) )
#compile
model.compile(loss='mse',metrics=['mae'],optimizer='adam')

In [29]:
###########
# 모델 학습
###########
model.fit(x,y,epochs=50)

Epoch 1/50
645/645 [==============================] - 2s 2ms/step - loss: 3177.6245 - mae: 10.6566
Epoch 2/50
645/645 [==============================] - 1s 2ms/step - loss: 2.3200 - mae: 1.1242
Epoch 3/50
645/645 [==============================] - 1s 2ms/step - loss: 1.6977 - mae: 1.0156
Epoch 4/50
645/645 [==============================] - 1s 2ms/step - loss: 1.3217 - mae: 0.9018
Epoch 5/50
645/645 [==============================] - 1s 2ms/step - loss: 1.0668 - mae: 0.8089
Epoch 6/50
645/645 [==============================] - 2s 3ms/step - loss: 1.0921 - mae: 0.7797
Epoch 7/50
645/645 [==============================] - 1s 2ms/step - loss: 0.8101 - mae: 0.6942
Epoch 8/50
645/645 [==============================] - 1s 2ms/step - loss: 0.7761 - mae: 0.6756
Epoch 9/50
645/645 [==============================] - 1s 2ms/step - loss: 1.2022 - mae: 0.7878
Epoch 10/50
645/645 [==============================] - 1s 2ms/step - loss: 1.2478 - mae: 0.7612
Epoch 11/50
645/645 [========================

In [30]:
###########
# 모델 예측
###########
y_pred = model.predict(x).reshape(-1)
y_pred[:5],y[:5]

645/645 [==============================] - 1s 1ms/step


(array([3.1238406, 3.6922991, 3.8579612, 3.4513118, 2.7649686],
       dtype=float32), array([4.526, 3.585, 3.521, 3.413, 3.422]))

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                288       
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 1)                 17        
                                                                 
Total params: 833
Trainable params: 833
Non-trainable params: 0
_________________________________________________________________
