# 1일차 Review : 같은 문제 다시 풀어보기
---
- 학습은 10번만!

In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()

In [3]:
x = iris.data
y = iris.target

In [4]:
x.shape, y.shape

((150, 4), (150,))

In [5]:
#################
# train/test set 분리
# tesetsize= 10%
# 난수고정 2023
#################
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=.1,random_state=2023)

In [6]:
#####################
# 라이브러리 불러오기
#####################
import tensorflow as tf
from tensorflow import keras

In [7]:
#######################
# 어떤 전처리 작업 필요
# Hint : y.shape
#######################
from tensorflow.keras.utils import to_categorical
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [14]:
########
# 모델링
########
keras.backend.clear_session()
model=keras.models.Sequential()

model.add( keras.layers.Input(shape=(4,)) )
model.add( keras.layers.Dense(32,activation='relu') )
model.add( keras.layers.Dense(16,activation='relu') )
model.add( keras.layers.Dense(3,activation='softmax') )

model.compile(loss='categorical_crossentropy',metrics=['acc'],optimizer='Adam')

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 32)                160       
                                                                 
 dense_1 (Dense)             (None, 16)                528       
                                                                 
 dense_2 (Dense)             (None, 3)                 51        
                                                                 
Total params: 739
Trainable params: 739
Non-trainable params: 0
_________________________________________________________________


In [21]:
###########
# 모델 학습
###########
model.fit(x_train,y_train,epochs=50)

Epoch 1/50
5/5 [==============================] - 0s 3ms/step - loss: 0.6657 - acc: 0.9407
Epoch 2/50
5/5 [==============================] - 0s 3ms/step - loss: 0.6367 - acc: 0.9556
Epoch 3/50
5/5 [==============================] - 0s 4ms/step - loss: 0.6079 - acc: 0.9481
Epoch 4/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5810 - acc: 0.9481
Epoch 5/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5533 - acc: 0.9407
Epoch 6/50
5/5 [==============================] - 0s 3ms/step - loss: 0.5321 - acc: 0.8667
Epoch 7/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5181 - acc: 0.8222
Epoch 8/50
5/5 [==============================] - 0s 3ms/step - loss: 0.4935 - acc: 0.8815
Epoch 9/50
5/5 [==============================] - 0s 4ms/step - loss: 0.4734 - acc: 0.9333
Epoch 10/50
5/5 [==============================] - 0s 3ms/step - loss: 0.4571 - acc: 0.9556
Epoch 11/50
5/5 [==============================] - 0s 4ms/step - loss: 0.4413 - acc: 0.95

In [22]:
###########
# 모델 예측
###########
y_pred = model.predict(x_test)
y_pred[:10], y_test[:10]


1/1 [==============================] - 0s 26ms/step


(array([[2.4916753e-04, 4.9749065e-02, 9.5000178e-01],
        [2.5824729e-02, 9.1131812e-01, 6.2857278e-02],
        [3.0799488e-02, 8.2426161e-01, 1.4493892e-01],
        [2.3625186e-04, 8.3149023e-02, 9.1661471e-01],
        [1.1126994e-02, 8.3983874e-01, 1.4903437e-01],
        [5.2656682e-04, 6.1390638e-02, 9.3808275e-01],
        [1.4229446e-02, 4.3854496e-01, 5.4722553e-01],
        [3.0968487e-02, 8.0449635e-01, 1.6453519e-01],
        [9.7782499e-01, 2.2158900e-02, 1.6060492e-05],
        [2.3493668e-02, 8.9606059e-01, 8.0445699e-02]], dtype=float32),
 array([[0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 0., 1.],
        [0., 1., 0.],
        [0., 1., 0.],
        [1., 0., 0.],
        [0., 1., 0.]], dtype=float32))

# 히든 레이어 추가하여 모델링!
---
- 조건
    - 히든 레이어 2개를 추가하여 다시 모델링!
    - 히든 레이어 노드 수 : 32
    - 히든 레이어 activation = 'relu'

In [ ]:
# data = ''
# target = ''
# x = data.drop(target,axis=1)
# y = data[target]
# x.shape,y.shape

In [25]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from sklearn.model_selection import *
from sklearn.metrics import *
from tensorflow.keras.utils import *

In [52]:
########
# 모델링
########
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=2023,test_size=0.1)

In [53]:
print('shape x,y ',x_train.shape,y_train.shape)
print('y_train unique',np.unique(y_train))
x_shape = x_train.shape[-1]
y_shape = len(np.unique(y_train))
dense_act = 'linear'
epochs = 50

if len(np.unique(y_train)) > 2:
    # when datset need one-hot-encoding
    y_train = to_categorical(y_train)
    y_test = to_categorical(y_test)
    dense_act = 'softmax'
    loss_func = 'categorical_crossentropy'

    print('y one-hot-encoded')
    print(' y unique',np.unique(y_train))



shape x,y  (135, 4) (135,)
y_train unique [0 1 2]
y one-hot-encoded
 y unique [0. 1.]


In [54]:
###########
# 모델 학습
###########
# 1. clear session
keras.backend.clear_session()
# 2. model set
model = keras.models.Sequential()
# 3. layer set
model.add( keras.layers.Input(shape=x_shape) )
model.add( keras.layers.Dense(64,activation='relu') )
model.add( keras.layers.Dense(32,activation='relu') )
model.add( keras.layers.Dense(32,activation='relu') )
model.add( keras.layers.Dense(16,activation='relu') )
model.add( keras.layers.Dense(y_shape, activation=dense_act) )
# 4. compile model
model.compile(loss='categorical_crossentropy',metrics=['acc'],optimizer='adam')
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 64)                320       
                                                                 
 dense_1 (Dense)             (None, 32)                2080      
                                                                 
 dense_2 (Dense)             (None, 32)                1056      
                                                                 
 dense_3 (Dense)             (None, 16)                528       
                                                                 
 dense_4 (Dense)             (None, 3)                 51        
                                                                 
Total params: 4,035
Trainable params: 4,035
Non-trainable params: 0
_________________________________________________________________


In [55]:
model.fit(x_train,y_train,epochs=epochs)

Epoch 1/50
5/5 [==============================] - 1s 6ms/step - loss: 1.1121 - acc: 0.3407
Epoch 2/50
5/5 [==============================] - 0s 4ms/step - loss: 0.9859 - acc: 0.4889
Epoch 3/50
5/5 [==============================] - 0s 4ms/step - loss: 0.8982 - acc: 0.8519
Epoch 4/50
5/5 [==============================] - 0s 4ms/step - loss: 0.8281 - acc: 0.8000
Epoch 5/50
5/5 [==============================] - 0s 4ms/step - loss: 0.7582 - acc: 0.7037
Epoch 6/50
5/5 [==============================] - 0s 4ms/step - loss: 0.7065 - acc: 0.8815
Epoch 7/50
5/5 [==============================] - 0s 3ms/step - loss: 0.6495 - acc: 0.8074
Epoch 8/50
5/5 [==============================] - 0s 5ms/step - loss: 0.5945 - acc: 0.7852
Epoch 9/50
5/5 [==============================] - 0s 4ms/step - loss: 0.5475 - acc: 0.9185
Epoch 10/50
5/5 [==============================] - 0s 4ms/step - loss: 0.4988 - acc: 0.9630
Epoch 11/50
5/5 [==============================] - 0s 4ms/step - loss: 0.4541 - acc: 0.94

In [59]:
###########
# 모델 예측
###########
y_pred = np.around(model.predict(x_test))
print(y_pred[:10])
print(y_test[:10])

1/1 [==============================] - 0s 23ms/step
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
[[0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]
